name: "copy to react-reference-ui-public"

on:
  push:
    branches: ['main']

jobs:
  copy-to-branches:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: write to public repo
      run: >
        mkdir -p ~/.ssh &&
        echo ${{ secrets.GH_SSH_SECRET }} > ~/.ssh/id_rsa &&
        chmod 600 ~/.ssh/id_rsa &&
        ssh-add -K ~/.ssh/id_rsa &&
        git remote add public https://github.com/soulmachines/react-reference-ui-public.git &&
        git push public main:main
