name: "copy to react-reference-ui-public"

on:
  push:
    branches: ['main']

jobs:
  copy-to-branches:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          git@github.com:soulmachines/react-reference-ui-public.git

